### ISSUE TITLE
[BUG] Can no longer type in the editor

### ISSUE THREAD

**Issue by ArrowAced** [mellobacon/Nucleus#30]
**Describe the bug**
Nothing happens when you try to type in the editor

**To Reproduce**
1. Open the editor
2. Try to type in it

**Expected behavior**
Typing in the editor should add what you type

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
Typing worked in previous versions

**Comment by mellobacon** [comment]
Editing seems to work for me in Linux. I did just push some code shortly before this bug was reported. Is this with the updated changes?

**Comment by ArrowAced** [comment]
Update: Backspacing seems to work but not typing. Huh

**Comment by mellobacon** [comment]
Weird....
Do you get any error in the inspector window (ctrl + shift + i)?

**Comment by ArrowAced** [comment]
I have these, but they might be unrelated

[Warning] <App> was created with unknown prop 'name' (bundle.js, line 61977)

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'file.content')
	(anonymous function) (bundle.js:45023)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob

**Comment by mellobacon** [comment]
Ah that's something. Weird that it cant read the file content...
What type of file were you trying to edit? And does the error message say which script the error is in other than bundle.js?

**Comment by ArrowAced** [comment]
The file's contents show up, just not able to be typed in.
> What type of file were you trying to edit?
I tried json, js, and txt if that's your question
> And does the error message say which script the error is in other than bundle.js?
Nope!

**Comment by mellobacon** [comment]
Ok so I think I managed to narrow down the bug but I haven't found a way to fix it. 
It might have something to do with these lines of code. I suspect there might be a conflict here between detecting input and keypresses but debugging this in Linux has proven difficult. Strangely only backspacing and adding new lines work.
https://github.com/mellobacon/Nucleus/blob/35dd900176134dbedb0e1cec11128cec64d52d31/src/components/Content/Editor/CodeMirrorEditor.svelte#L53-L68

I'm opening this bug up to others if they want to attempt to fix this as well because honestly I'm stumped.
